name: 'create UML diagrams using mermaid from c# enitity classes'
description: 'create UML diagrams using mermaid from c# classes'
branding:
  icon: arrow-right-circle
  color: black
inputs:
  path-to-entities:
    description: 'Path to entities'
    required: true
    default: 'unknown'
  uml-file:
    description: 'File to update. Default to UML.md'
    required: true
    default: 'UML.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path-to-entities }}
    - ${{ inputs.uml-file }}
  entrypoint: "/app/entrypoint.sh"
